Resources:
  ApiGatewayStagedev:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      DeploymentId: !GetAtt ApiGatewayDeployment.DeploymentId
      StageName: dev
      CacheClusterSize: "0.5"
      TracingEnabled: false
      CacheClusterEnabled: false

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: REST API with GET endpoint which triggers a Lambda function that fetches a quote.
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
      DisableExecuteApiEndpoint: false
      Name: quote-api-cftest1

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethodquote
    Properties:
      Description: Initial deployment, dev stage.
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayMethodquote:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - ApiGatewayRestApi
      - ApiGatewayResourcequote
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourcequote
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
        Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:577224486130:function:quote-fetcher-cftest1/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty

  ApiGatewayMethodpopulate:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - ApiGatewayRestApi
      - ApiGatewayResourcepopulate
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResourcepopulate
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: ""
        Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:577224486130:function:quote-writer-cftest1/invocations
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty

  ApiGatewayResourcequote:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: quote

  ApiGatewayResourcepopulate:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: populate

  LambdaFunctionquotefetcher:
    Type: AWS::Lambda::Function
    Properties:
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Handler: quote_fetcher.lambda_handler
      Code:
        S3Bucket: quote-app-source
        S3Key: quote_fetcher.zip
      Role: !GetAtt IAMRolequotefetcher.Arn
      FunctionName: quote-fetcher-cftest1
      Runtime: python3.12
      PackageType: Zip
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/quote-fetcher-cftest1
      RecursiveLoop: Terminate
      Environment:
        Variables:
          s3_logfile: quote-log.txt
          s3_bucket: quotes-cftest1
          dynamodb_table: quotes-cftest1
      Timeout: 10

  LambdaPermissionquotefetcher:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunctionquotefetcher
    Properties:
      FunctionName: !GetAtt LambdaFunctionquotefetcher.Arn
      Action: lambda:InvokeFunction
      SourceArn: !Join
        - ""
        - - 'arn:aws:execute-api:us-east-1:577224486130:'
          - !GetAtt ApiGatewayRestApi.RestApiId
          - /*/GET/quote
      Principal: apigateway.amazonaws.com

  LambdaFunctionquotewriter:
    Type: AWS::Lambda::Function
    Properties:
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
      Handler: quote_writer.lambda_handler
      Code:
        S3Bucket: quote-app-source
        S3Key: quote_writer.zip
      Role: !GetAtt IAMRolequotewriter.Arn
      FunctionName: quote-writer-cftest1
      Runtime: python3.12
      PackageType: Zip
      LoggingConfig:
        LogFormat: Text
        LogGroup: /aws/lambda/quote-writer-cftest1
      RecursiveLoop: Terminate
      Environment:
        Variables:
          source_bucket: quote-app-source
          quotes_source_file: quotes.csv
          dynamodb_table: quotes-cftest1
      Timeout: 30

  LambdaPermissionquotewriter:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunctionquotewriter
    Properties:
      FunctionName: !GetAtt LambdaFunctionquotewriter.Arn
      Action: lambda:InvokeFunction
      SourceArn: !Join
        - ""
        - - 'arn:aws:execute-api:us-east-1:577224486130:'
          - !GetAtt ApiGatewayRestApi.RestApiId
          - /*/GET/populate
      Principal: apigateway.amazonaws.com

  S3Buckequote:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: quotes-cftest1
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  DynamoDBTablequotes:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: quotes-cftest1
      AttributeDefinitions:
        - AttributeType: S
          AttributeName: quote_id
      BillingMode: PROVISIONED
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
      KeySchema:
        - KeyType: HASH
          AttributeName: quote_id
      TableClass: STANDARD

  IAMRolequotefetcher:
    Type: AWS::IAM::Role
    DependsOn:
      - IAMManagedPolicyLambdaBasicExecutionRolequotefetcher
      - IAMManagedPolicypolicydynamodbquoteread
      - IAMManagedPolicypolicys3quotelogread
      - IAMManagedPolicypolicys3quotelogwrite
    Properties:
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::577224486130:policy/service-role/IAMManagedPolicyLambdaBasicExecutionRolequotefetcher
        - arn:aws:iam::577224486130:policy/dynamo-db-quotes-table-read-cftest1
        - arn:aws:iam::577224486130:policy/s3-quote-log-write-cftest1
        - arn:aws:iam::577224486130:policy/s3-quote-log-read-cftest1
      MaxSessionDuration: 3600
      RoleName: quote-fetcher-role-cftest1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

  IAMManagedPolicyLambdaBasicExecutionRolequotefetcher:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: IAMManagedPolicyLambdaBasicExecutionRolequotefetcher
      Path: /service-role/
      Description: ""
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: arn:aws:logs:us-east-1:577224486130:*
            Action: logs:CreateLogGroup
            Effect: Allow
          - Resource:
              - arn:aws:logs:us-east-1:577224486130:log-group:/aws/lambda/quote-fetcher-cftest1:*
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow

  IAMManagedPolicypolicydynamodbquoteread:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: dynamo-db-quotes-table-read-cftest1
      Path: /
      Description: Policy with GetItem permission to the quotes table.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - arn:aws:dynamodb:*:577224486130:table/quotes-cftest1/index/quote_id
              - arn:aws:dynamodb:*:577224486130:table/quotes-cftest1
            Action:
              - dynamodb:GetItem
              - dynamodb:Scan
            Effect: Allow
            Sid: VisualEditor0

  IAMManagedPolicypolicys3quotelogread:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3-quote-log-read-cftest1
      Path: /
      Description: Policy with getObject read access to quotes-cftest1 bucket.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: arn:aws:s3:::quotes-cftest1/*
            Action: s3:GetObject
            Effect: Allow
            Sid: VisualEditor0

  IAMManagedPolicypolicys3quotelogwrite:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3-quote-log-write-cftest1
      Path: /
      Description: Policy with putObject permissions to the quote-log.txt object in the quote-log bucket.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: arn:aws:s3:::quotes-cftest1/quote-log.txt
            Action: s3:PutObject
            Effect: Allow
            Sid: VisualEditor0

  IAMRolequotewriter:
    Type: AWS::IAM::Role
    DependsOn:
      - IAMManagedPolicyAWSLambdaBasicExecutionRolequotewriter
      - IAMManagedPolicydynamodbquotewrite
      - IAMManagedPolicypolicys3quoteread
    Properties:
      Path: /service-role/
      ManagedPolicyArns:
        - arn:aws:iam::577224486130:policy/service-role/IAMManagedPolicyAWSLambdaBasicExecutionRolequotewriter
        - arn:aws:iam::577224486130:policy/dynamo-db-quotes-table-writer-cftest1
        - arn:aws:iam::577224486130:policy/s3-quote-read-cftest1
      RoleName: quote-writer-role-cftest1
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

  IAMManagedPolicyAWSLambdaBasicExecutionRolequotewriter:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: IAMManagedPolicyAWSLambdaBasicExecutionRolequotewriter
      Path: /service-role/
      Description: ""
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: arn:aws:logs:us-east-1:577224486130:*
            Action: logs:CreateLogGroup
            Effect: Allow
          - Resource:
              - arn:aws:logs:us-east-1:577224486130:log-group:/aws/lambda/quote-writer-cftest1:*
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow

  IAMManagedPolicydynamodbquotewrite:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: dynamo-db-quotes-table-writer-cftest1
      Path: /
      Description: Policy with PutItem and BatchWriteItem permission to the quotes table.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - arn:aws:dynamodb:*:577224486130:table/quotes-cftest1/index/quote_id
              - arn:aws:dynamodb:*:577224486130:table/quotes-cftest1
            Action:
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
            Effect: Allow
            Sid: VisualEditor0

  IAMManagedPolicypolicys3quoteread:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: s3-quote-read-cftest1
      Path: /
      Description: Policy with GetObject permissions to the quotes.csv object in the quotes bucket.
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource: arn:aws:s3:::quotes-cftest1/quotes.csv
            Action: s3:GetObject
            Effect: Allow
            Sid: VisualEditor0